"""
repl_env.py

Persistent REPL environment for Recursive Medical Language Model (R-MedLM)
"""

import io
import traceback
from contextlib import redirect_stdout

from tools import sql_tools, patient_tools, lab_tools, vitals_tools, cohort_tools, stats_tools


class REPLEnvironment:
    def __init__(self):
        self.globals = self._initialize_globals()

    def _initialize_globals(self):
        """
        Defines the global namespace available to the LLM-written code.
        Only safe, approved tools are exposed.
        """
        return {
            "sql_tools": sql_tools,
            "patient_tools": patient_tools,
            "lab_tools": lab_tools,
            "vitals_tools": vitals_tools,
            "cohort_tools": cohort_tools,
            "stats_tools": stats_tools,
        }

    def execute(self, code: str):
        """
        Executes code generated by the model.
        Captures stdout and errors without crashing the loop.
        """
        stdout_buffer = io.StringIO()

        try:
            with redirect_stdout(stdout_buffer):
                exec(code, self.globals)

            output = stdout_buffer.getvalue()
            return {
                "success": True,
                "stdout": output,
                "error": None,
                "variables": list(self.globals.keys())
            }

        except SyntaxError as e:
            return {
                "success": False,
                "stdout": stdout_buffer.getvalue(),
                "error": f"SyntaxError: {e.msg} at line {e.lineno}: {e.text}",
                "variables": list(self.globals.keys())
            }

        except Exception as e:
            # Get the last few lines of traceback for context
            tb_lines = traceback.format_exc().strip().split('\n')
            short_tb = '\n'.join(tb_lines[-3:]) if len(tb_lines) > 3 else '\n'.join(tb_lines)
            return {
                "success": False,
                "stdout": stdout_buffer.getvalue(),
                "error": f"{type(e).__name__}: {e}\n{short_tb}",
                "variables": list(self.globals.keys())
            }

    def get_variable(self, name):
        return self.globals.get(name, None)

    def set_variable(self, name, value):
        self.globals[name] = value