"""
repl_env.py

Persistent REPL environment for Recursive Medical Language Model (R-MedLM)
"""

import io
import traceback
from contextlib import redirect_stdout

from tools import sql_tools, patient_tools, lab_tools, vitals_tools, cohort_tools, stats_tools


class REPLEnvironment:
    def __init__(self):
        self.globals = self._initialize_globals()

    def _initialize_globals(self):
        """
        Defines the global namespace available to the LLM-written code.
        Only safe, approved tools are exposed.
        """
        return {
            "sql_tools": sql_tools,
            "patient_tools": patient_tools,
            "lab_tools": lab_tools,
            "vitals_tools": vitals_tools,
            "cohort_tools": cohort_tools,
            "stats_tools": stats_tools,
        }

    def execute(self, code: str):
        """
        Executes code generated by the model.
        Captures stdout and errors without crashing the loop.
        """
        stdout_buffer = io.StringIO()

        try:
            with redirect_stdout(stdout_buffer):
                try:
                    exec(code, self.globals)
                except Exception as e:
                    print("⚠️ Execution error:", e)

            output = stdout_buffer.getvalue()
            return {
                "success": True,
                "stdout": output,
                "error": None,
                "variables": list(self.globals.keys())
            }

        except Exception:
            return {
                "success": False,
                "stdout": stdout_buffer.getvalue(),
                "error": traceback.format_exc(),
                "variables": list(self.globals.keys())
            }

    def get_variable(self, name):
        return self.globals.get(name, None)

    def set_variable(self, name, value):
        self.globals[name] = value